apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    app: hello-worldapp
    environment: stage
spec:
  containers:
    - name: first
      image: hello-world
      ports:
        - containerPort: 80