---
apiVersion: v1
kind: Pod
metadata: 
  name: mysql
  namespace: default
  labels:
    name: mysql
    purpose: learning
spec:
  containers:
    - name: mysqlcontainer
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        - name: MYSQL_DATABASE
          value: author
        - name: MYSQL_USER
          value: admin
        - name : MYSQL_PASSWORD
          value: admin
      ports:
        - containerPort: 3306
      # resources:
      #   requests:
      #     memory: "250Mi"
      #     cpu: "250m"
      #   limits:
      #     memory: "500Mi"
      #     cpu: "500m"