apiVersion: v1
kind: Pod
metadata:
  name: nop
  labels:
    app: nopapp
    appversion: v1
spec:
  containers:
    - name: nopcoontainer
      image: shaikkhajaibrahim/nopcommercejune2024:070624
      ports: 
        - containerPort: 5000
          protocol: TCP