---
apiVersion: v1
kind: Pod
metadata:
  name: srpingpetclinic
  labels:
    environment: stage
    app: java
spec:
  containers:
    - name: spring-petclinic
      image: shaikkhajaibrahim/spc
      # resources:
      #   requests:
      #     memory: "250Mi"
      #     cpu: "250Mi"
      #   limits:
      #     memory: "500Mi"
      #     cpu: "500m"
      ports:
        - containerPort: 8080