---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mypod
  labels:
    app: BE
spec:
  replicas: 2
  selector:
    matchLabels:
      app: BE
  template:
    metadata:
      name: mypod
      labels:
        app: BE
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            failureThreshold: 2
            successThreshold: 1
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            failureThreshold: 2
            successThreshold: 1
            periodSeconds: 10
          # resources:
          #   limits:
          #     cpu: "200Mi"
          #     memory: "500m"