---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dep
spec:
  minReadySeconds: 22
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: web
        version: v3
    spec:
      containers:
        - name: webcontainer
          image: shaikkhajaibrahim/dmtest:3.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
          startupProbe:
            initialDelaySeconds: 2
            successThreshold: 1
            failureThreshold: 1
            periodSeconds: 10
            httpGet:
              path: /
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP