---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
  labels:
    db: mysql
data:
  MYSQL_ROOT_PASSWORD: admin
  MYSQL_DATABASE: author
  MYSQL_USER: admin
  MYSQL_PASSWORD: admin

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    db: mysql
spec:
  containers:
    - name: test
      image: alpine
      volumeMounts:
        - name: configvolume
          mountPath: /config
  volumes: 
    - name: configvolume
      configMap:
        name: mysql-cm
        