---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd
  labels:
    name: myapp
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        name: myapp
        env: dev
    spec:
      containers:
        - name: mycontainer
          image: httpd
          ports:
            - containerPort: 8080