---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pet
  labels:
    name: petclinic
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      name: petclinic
  template:
    metadata:
      labels:
        name: petclinic
        env: dev
    spec:
      containers:
        - name: petcontainer
          image: shaikkhajaibrahim/spc
          ports:
            - containerPort: 8080