---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4=
  MYSQL_DATABASE: YXV0aG9y
  MYSQL_USER: YWRtaW4=
  MYSQL_PASSWORD: YWRtaW4=

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    db: mysql
spec:
  containers:
    - name: mysql-cont
      image: mysql:latest
      envFrom:
        - secretRef:
            name: mysql-secret
  