---
- name: install java on the machine
  ansible.builtin.apt:
    name: "{{ java_version }}"
    state: latest
    update_cache: yes
- name: create tomcat group if not present
  ansible.builtin.group:
    name: "{{ group }}"
    state: present
- name: add user to the tomcat home dirrectory
  ansible.builtin.user:
    name: "{{ user }}"
    groups: "{{ group }}"
    append: yes
    home: "{{ home_dir }}"
    shell: /bin/false
- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: https://dlcdn.apache.org/tomcat/tomcat-10/v{{version}}/bin/apache-tomcat-{{version}}-fulldocs.tar.gz
    dest: "{{ home_dir }}"
    remote_src: yes
- name: Create a symbolic link
  ansible.builtin.file:
    src: "{{home_dir}}/apache-tomcat-${{version}"
    dest: "{{home_dir}}/latest"
    owner: "{{ user }}"
    group: "{{ group }}"
    state: link
- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: "{{ home_dir }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    recurse: yes
    mode: '0644'
- name: Copy service file to systemd
  ansible.builtin.copy:
    src: apache.service.j2
    dest: /etc/systemd/system/tomcat.service
    remote_src: yes
- name: daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: Start service apache, if not started
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes