---
- name: deploying apache 10 on ubuntu machine
  hosts: webservers
  become: yes
  tasks:
    - name: install java on the machine
      ansible.builtin.apt:
        name: "{{ java_version }}"
        state: present
        update_cache: yes
    - name: create user groups
      ansible.builtin.group:
        name: "{{ group }}"
        state: present
    - name: create a system user
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /bin/false
        groups: "{{ user }}"
        home: "{{ home_dir }}"
        password: "*"
    - name: download tomcat zip ad unzip the file to a location
      ansible.builtin.unarchive:
        src: https://archive.apache.org/dist/tomcat/tomcat-10/v{{ VERSION }}/bin/apache-tomcat-{{ VERSION }}.tar.gz
        dest: "{{ home_dir }}"
        remote_src: yes
    - name: Create a symbolic link
      ansible.builtin.file:
        src: "{{ home_dir }}/apache-tomcat-${{ VERSION }}"
        dest: "{{ home_dir }}/latest"
        owner: "{{ user }}"
        group: "{{ user }}"
        state: link
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: "{{ home_dir }}"
        state: directory
        recurse: yes
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
    - name: shell script must be executable
      ansible.builtin.shell:
        cmd: chmod +x /opt/tomcat/latest/bin/*.sh
        executable: /bin/bash
    - name: copy service file to target
      ansible.builtin.copy:
        src: /tomcat.service
        dest: /etc/systemd/system/tomcat.service
    - name: reload systemd daemon
      ansible.builtin.systemd_service:
        daemon_reload: true
    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: apache2
        state: started